[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bautista Berenfeld", email = "bbautista2026ipf@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "ruff>=0.16.4",
]

[project.scripts]
workspace = "workspace:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
